# ============================================================================
# ATTRIBUTION: The keyword fallback logic and confidence-weighting strategies
# are inspired by the semi-supervised alert clustering methods evaluated in:
# "Semi-Supervised Alert Filtering" (Electronics 2023, 12, 4755).
# ============================================================================
import re
import logging

logger = logging.getLogger(__name__)

class TriageParser:
    @staticmethod
    def parse_llm_response(raw_text):
        """
        Advanced Robust Parsing: Case-insensitive text normalization and heuristic extraction.
        Translates unstructured, non-compliant LLM text generations into structured, validated schemas.
        """
        if not raw_text:
            return {
                "classification": "Unknown",
                "confidence_score": 0.0,
                "explanation": "No response text was generated by the local model."
            }

        # Normalize casing to eliminate token capitalization errors
        normalized_text = raw_text.lower()
        classification = None
        confidence_score = 0.5  # Default middle ground
        explanation = ""

        # ==========================================
        # 1. CLASSIFICATION EXTRACTION
        # ==========================================
        # Strategy 1: Explicit Label-Based Parsing
        # Try to find structured delimiters matching "classification: label"
        label_match = re.search(r"classification\s*:\s*([a-z]+)", normalized_text)
        if label_match:
            candidate = label_match.group(1).strip()
            if "vulnerability" in candidate:
                classification = "Vulnerability"
            elif "normal" in candidate:
                classification = "Normal"

        # Strategy 2: Global Keyword-Based Heuristic Search (Fallback)
        if not classification:
            # Check for high-criticality keywords
            if any(word in normalized_text for word in ["vulnerability", "malicious", "exploit", "attack", "compromise"]):
                classification = "Vulnerability"
            # Check for benign-indicative keywords
            elif any(word in normalized_text for word in ["normal", "benign", "expected", "safe", "authorized"]):
                classification = "Normal"
            else:
                classification = "Unknown"

        # ==========================================
        # 2. CONFIDENCE SCORE EXTRACTION
        # ==========================================
        # Scan for explicit decimal fractions (e.g., 0.85, 0.90) or percentages
        confidence_match = re.search(r"confidence(?:_score)?\s*:\s*(0\.\d+|1\.0|\d+%)", normalized_text)
        if confidence_match:
            score_str = confidence_match.group(1)
            if "%" in score_str:
                confidence_score = float(score_str.replace("%", "")) / 100.0
            else:
                confidence_score = float(score_str)
        else:
            # Assign heuristic confidence based on model language markers
            if "highly likely" in normalized_text or "high confidence" in normalized_text:
                confidence_score = 0.90
            elif "possible alternative" in normalized_text or "uncertain" in normalized_text:
                confidence_score = 0.60
            elif classification == "Normal":
                confidence_score = 0.80  # Default normal confidence
            elif classification == "Vulnerability":
                confidence_score = 0.85  # Default vulnerability confidence

        # ==========================================
        # 3. EXPLANATION EXTRACTION
        # ==========================================
        # Strategy 1: Structured Section Demarcation
        # Look for the EXPLANATION segment
        explanation_match = re.search(r"explanation\s*:\s*(.*)", raw_text, re.IGNORECASE | re.DOTALL)
        if explanation_match:
            explanation = explanation_match.group(1).strip()
        else:
            # Fallback: Clean the raw text and present it as the logical explanation
            # Remove any JSON brackets if the model tried to output them
            clean_text = re.sub(r"[{}\"']", "", raw_text)
            explanation = clean_text.strip()

        # Final structural sanitization
        return {
            "classification": classification if classification else "Unknown",
            "confidence_score": round(confidence_score, 2),
            "explanation": explanation if explanation else "No written rationale was extracted from the response."
        }
